const url='https://study-2gurue827a3a5449-1300561635.ap-shanghai.app.tcloudbase.com/container-messagewall/sampledata'
Page({
  data:{
    name:'',
    sex:'',
    sno:'',
    satisfaction:'',
    skills:[],
    opinion:'',
    control:true,
    control2:false
  },
  onLoad(){
    wx.request({
      url,
      method:'get',
      success:res=>{
        console.log(res)
        if(res.data.gender==1){
          this.setData({
            control:true,
            control2:false
          })
        }else if(res.data.gender==0){
          this.setData({
            control:false,
            control2:true
          })
        }
        this.setData({
          name:res.data.name,
          opinion:res.data.opinion,
          skills:res.data.skills,
          satisfaction:res.data.satisfaction,
          sno:res.data.sno
        })
      },
      fail(res){
        console.log(res)
      }
    })
  },
  submit(e){
    console.log(e)
    wx.request({
      url,
      method:'post',
      data:e.detail.value,
      success:res=>{
        console.log(res)
        if(res.data.gender==1){
          this.setData({
            control:true,
            control2:false
          })
        }else if(res.data.gender==0){
          this.setData({
            control:false,
            control2:true
          })
        }
        this.setData({
          name:res.data.name,
          sex:res.data.gender,
          opinion:res.data.opinion,
          skills:res.data.skills,
          satisfaction:res.data.satisfaction,
          sno:res.data.sno
        })
      },
      fail(res){
        console.log(res)
      }
    })
  }
})