Page({
  data:{
    markers:[
      {
        id:1,
        longitude:113.4464,
        latitude:23.3872,
        iconPath:'./images/mark.png',
        label:{
          content:'图文中心',
          color:'#369',
        }
      },
      {
        id:2,
        longitude:113.4480,
        latitude:23.3880,
        iconPath:'./images/mark.png',
        label:{
          content:'教学楼',
          color:'#369',
        }
      },
    ]
  }
})